name = "baojie-ngpart-report"
main = "src/index.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "parts_ng_report_db"
database_id = "1941a5d7-67c4-4782-a59e-eab78ee71c15"
